# Generated by Django 5.2.4 on 2025-08-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusuario',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('APOYO', 'Apoyo'), ('DOCENTE', 'Docente'), ('INVITADO', 'Invitado')], max_length=15),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('APOYO', 'Apoyo'), ('DOCENTE', 'Docente'), ('INVITADO', 'Invitado')], max_length=15),
        ),
    ]
