# Generated by Django 5.2.4 on 2025-10-29 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0002_initial'),
        ('usuarios', '0002_alter_usuario_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='departamento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='departamentos.departamento'),
        ),
    ]
