# Generated by Django 5.2.4 on 2025-09-22 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0004_alter_departamento_nombre_and_more'),
        ('usuarios', '0002_alter_historicalusuario_role_alter_usuario_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='departamentos.departamento', unique=True),
        ),
    ]
