# Generated by Django 5.2.4 on 2025-11-04 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0007_remove_evidencia_ciclo_and_more'),
        ('riesgos', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalriesgo',
            name='meta',
        ),
        migrations.RemoveField(
            model_name='riesgo',
            name='meta',
        ),
        migrations.AddField(
            model_name='historicalriesgo',
            name='actividad',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='actividades.actividad'),
        ),
        migrations.AddField(
            model_name='riesgo',
            name='actividad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='actividades.actividad'),
            preserve_default=False,
        ),
    ]
