# Generated by Django 5.2.4 on 2025-11-12 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0007_remove_evidencia_ciclo_and_more'),
        ('riesgos', '0003_remove_historicalriesgo_meta_remove_riesgo_meta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riesgo',
            name='actividad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='actividades.actividad'),
        ),
    ]
