# Generated by Django 5.2.4 on 2025-10-09 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objetivos', '0003_initial'),
        ('proyectos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproyecto',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalproyecto',
            name='objetivo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='objetivos.objetivoestrategico'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='objetivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='objetivos.objetivoestrategico'),
        ),
    ]
