# Generated by Django 5.2.4 on 2025-10-09 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objetivos', '0001_initial'),
        ('programas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalobjetivoestrategico',
            name='ciclo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='programas.ciclo'),
        ),
    ]
