# Generated by Django 5.2.4 on 2025-10-29 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objetivos', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalobjetivoestrategico',
            name='ciclo',
        ),
        migrations.RemoveField(
            model_name='objetivoestrategico',
            name='ciclo',
        ),
    ]
