# Generated by Django 5.2.4 on 2025-10-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objetivos', '0004_remove_historicalobjetivoestrategico_ciclo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalobjetivoestrategico',
            name='clave',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='objetivoestrategico',
            name='clave',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
