# Generated by Django 5.2.4 on 2025-10-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciclo',
            name='nombre',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalciclo',
            name='nombre',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
