# Generated by Django 5.2.4 on 2025-08-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciclo',
            name='activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalciclo',
            name='activo',
            field=models.BooleanField(default=False),
        ),
    ]
