# Generated by Django 5.2.4 on 2025-11-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0003_ciclo_nombre_historicalciclo_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciclo',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='historicalciclo',
            name='activo',
        ),
        migrations.AddField(
            model_name='ciclo',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activa'), ('Inactivo', 'En Proceso'), ('En proceso', 'No Cumplida')], default='Activo', max_length=15),
        ),
        migrations.AddField(
            model_name='historicalciclo',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activa'), ('Inactivo', 'En Proceso'), ('En proceso', 'No Cumplida')], default='Activo', max_length=15),
        ),
    ]
