# Generated by Django 5.2.4 on 2025-09-01 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0003_ciclo_activo_historicalciclo_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciclo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='historicalciclo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='historicalprogramaestrategico',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='programaestrategico',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
