# Generated by Django 5.2.4 on 2025-11-03 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0004_remove_ciclo_activo_remove_historicalciclo_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciclo',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activa'), ('Inactivo', 'Inactivo'), ('En proceso', 'En proceso')], default='Activo', max_length=15),
        ),
        migrations.AlterField(
            model_name='ciclo',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalciclo',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activa'), ('Inactivo', 'Inactivo'), ('En proceso', 'En proceso')], default='Activo', max_length=15),
        ),
        migrations.AlterField(
            model_name='historicalciclo',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
