# Generated by Django 5.2.4 on 2025-09-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0004_alter_ciclo_activo_alter_historicalciclo_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprogramaestrategico',
            name='duracion',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='programaestrategico',
            name='duracion',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
