# Generated by Django 5.2.4 on 2025-08-19 15:15

import django.db.models.deletion
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMeta',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=250, null=True)),
                ('clave', models.CharField(db_index=True, max_length=40)),
                ('enunciado', models.TextField()),
                ('indicador', models.TextField()),
                ('unidadMedida', models.TextField()),
                ('metodoCalculo', models.TextField()),
                ('lineBase', models.FloatField(blank=True, null=True)),
                ('metaCumplir', models.FloatField(blank=True, null=True)),
                ('variableB', models.FloatField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical meta',
                'verbose_name_plural': 'historical metas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMetaComprometida',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('valor', models.IntegerField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical meta comprometida',
                'verbose_name_plural': 'historical meta comprometidas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=250, null=True)),
                ('clave', models.CharField(max_length=40, unique=True)),
                ('enunciado', models.TextField()),
                ('indicador', models.TextField()),
                ('unidadMedida', models.TextField()),
                ('metodoCalculo', models.TextField()),
                ('lineBase', models.FloatField(blank=True, null=True)),
                ('metaCumplir', models.FloatField(blank=True, null=True)),
                ('variableB', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetaComprometida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AvanceMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avance', models.CharField(max_length=500)),
                ('fecha_registro', models.DateField()),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='departamentos.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalAvanceMeta',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('avance', models.CharField(max_length=500)),
                ('fecha_registro', models.DateField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('departamento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='departamentos.departamento')),
            ],
            options={
                'verbose_name': 'historical avance meta',
                'verbose_name_plural': 'historical avance metas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
