# Generated by Django 5.2.4 on 2025-10-09 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamentos', '0002_initial'),
        ('metas', '0001_initial'),
        ('programas', '0001_initial'),
        ('proyectos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalavancemeta',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalmeta',
            name='ciclo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='programas.ciclo'),
        ),
        migrations.AddField(
            model_name='historicalmeta',
            name='departamento',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='departamentos.departamento'),
        ),
        migrations.AddField(
            model_name='historicalmeta',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalmeta',
            name='proyecto',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='proyectos.proyecto'),
        ),
        migrations.AddField(
            model_name='historicalmetacomprometida',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meta',
            name='ciclo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programas.ciclo'),
        ),
        migrations.AddField(
            model_name='meta',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='departamentos.departamento'),
        ),
        migrations.AddField(
            model_name='meta',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='proyectos.proyecto'),
        ),
        migrations.AddField(
            model_name='historicalmetacomprometida',
            name='meta',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='metas.meta'),
        ),
        migrations.AddField(
            model_name='historicalavancemeta',
            name='metaCumplir',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='metas.meta'),
        ),
        migrations.AddField(
            model_name='avancemeta',
            name='metaCumplir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='metas.meta'),
        ),
        migrations.AddField(
            model_name='metacomprometida',
            name='meta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='metas.meta'),
        ),
    ]
