# Generated by Django 5.2.4 on 2025-10-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmeta',
            name='clave',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='meta',
            name='clave',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
