# Generated by Django 5.2.4 on 2025-08-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avancemeta',
            name='avance',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='historicalavancemeta',
            name='avance',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmeta',
            name='lineBase',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmeta',
            name='metaCumplir',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmeta',
            name='variableB',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmetacomprometida',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='meta',
            name='lineBase',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='meta',
            name='metaCumplir',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='meta',
            name='variableB',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='metacomprometida',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True),
        ),
    ]
