# Generated by Django 5.2.4 on 2025-08-20 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0003_alter_avancemeta_avance_and_more'),
        ('programas', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmetacomprometida',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='metacomprometida',
            name='departamento',
        ),
        migrations.AddField(
            model_name='historicalmetacomprometida',
            name='programa',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='programas.programaestrategico'),
        ),
        migrations.AddField(
            model_name='metacomprometida',
            name='programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='programas.programaestrategico'),
        ),
    ]
