# Generated by Django 5.2.4 on 2025-10-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0003_alter_historicalmeta_clave_alter_meta_clave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmeta',
            name='enunciado',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='meta',
            name='enunciado',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
