# Generated by Django 5.2.4 on 2025-08-25 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0004_remove_historicalmetacomprometida_departamento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalmeta',
            old_name='lineBase',
            new_name='lineaBase',
        ),
        migrations.RenameField(
            model_name='meta',
            old_name='lineBase',
            new_name='lineaBase',
        ),
    ]
