# Generated by Django 5.2.4 on 2025-11-02 04:21

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0004_alter_historicalmeta_enunciado_alter_meta_enunciado'),
        ('programas', '0003_ciclo_nombre_historicalciclo_nombre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmeta',
            name='ciclo',
        ),
        migrations.RemoveField(
            model_name='historicalmeta',
            name='lineabase',
        ),
        migrations.RemoveField(
            model_name='historicalmeta',
            name='metacumplir',
        ),
        migrations.RemoveField(
            model_name='meta',
            name='ciclo',
        ),
        migrations.RemoveField(
            model_name='meta',
            name='lineabase',
        ),
        migrations.RemoveField(
            model_name='meta',
            name='metacumplir',
        ),
        migrations.AddField(
            model_name='avancemeta',
            name='ciclo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programas.ciclo'),
        ),
        migrations.AddField(
            model_name='historicalavancemeta',
            name='ciclo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='programas.ciclo'),
        ),
        migrations.AddField(
            model_name='historicalmetacomprometida',
            name='ciclo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='programas.ciclo'),
        ),
        migrations.AddField(
            model_name='metacomprometida',
            name='ciclo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programas.ciclo'),
        ),
        migrations.CreateModel(
            name='HistoricalMetaCiclo',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('lineaBase', models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True)),
                ('metaCumplir', models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('ciclo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='programas.ciclo')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('meta', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='metas.meta')),
            ],
            options={
                'verbose_name': 'historical meta ciclo',
                'verbose_name_plural': 'historical meta ciclos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MetaCiclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lineaBase', models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True)),
                ('metaCumplir', models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas_ciclo', to='programas.ciclo')),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas_ciclo', to='metas.meta')),
            ],
            options={
                'unique_together': {('meta', 'ciclo')},
            },
        ),
    ]
