# Generated by Django 5.2.4 on 2025-11-02 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0005_remove_historicalmeta_ciclo_and_more'),
        ('programas', '0003_ciclo_nombre_historicalciclo_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metaciclo',
            name='ciclo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metas_ciclo', to='programas.ciclo'),
        ),
    ]
