# Generated by Django 5.2.4 on 2025-08-25 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0006_rename_lineabase_historicalmeta_lineabase_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalmeta',
            old_name='metaCumplir',
            new_name='metacumplir',
        ),
        migrations.RenameField(
            model_name='meta',
            old_name='metaCumplir',
            new_name='metacumplir',
        ),
    ]
