# Generated by Django 5.2.4 on 2025-11-04 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0006_alter_metaciclo_ciclo'),
        ('programas', '0005_alter_ciclo_estado_alter_ciclo_nombre_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='metacomprometida',
            unique_together={('meta', 'ciclo')},
        ),
    ]
