# Generated by Django 5.2.4 on 2025-08-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0008_historicalmeta_porcentages_meta_porcentages'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmeta',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='meta',
            name='activa',
            field=models.BooleanField(default=True),
        ),
    ]
