# Generated by Django 5.2.4 on 2025-08-25 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0010_alter_historicalmeta_activa_alter_meta_activa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmeta',
            name='activa',
        ),
        migrations.RemoveField(
            model_name='meta',
            name='activa',
        ),
    ]
