# Generated by Django 5.2.4 on 2025-08-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0011_remove_historicalmeta_activa_remove_meta_activa'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmeta',
            name='activa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meta',
            name='activa',
            field=models.BooleanField(default=False),
        ),
    ]
