# Generated by Django 5.2.4 on 2025-09-06 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0012_historicalmeta_activa_meta_activa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avancemeta',
            name='metaCumplir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='metas.meta'),
        ),
        migrations.AlterField(
            model_name='historicalmeta',
            name='clave',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='meta',
            name='clave',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='metacomprometida',
            name='meta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='metas.meta'),
        ),
    ]
