# Generated by Django 5.2.4 on 2025-09-09 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0013_alter_avancemeta_metacumplir_and_more'),
        ('programas', '0006_alter_historicalprogramaestrategico_duracion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmetacomprometida',
            name='programa',
        ),
        migrations.RemoveField(
            model_name='metacomprometida',
            name='programa',
        ),
        migrations.AddField(
            model_name='historicalmeta',
            name='ciclo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='programas.ciclo'),
        ),
        migrations.AddField(
            model_name='meta',
            name='ciclo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programas.ciclo'),
        ),
    ]
