# Generated by Django 5.2.4 on 2025-10-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0014_remove_historicalmetacomprometida_programa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmeta',
            name='acumulable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meta',
            name='acumulable',
            field=models.BooleanField(default=False),
        ),
    ]
