# Generated by Django 5.2.4 on 2025-10-09 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividades', '0002_initial'),
        ('metas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='meta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='metas.meta'),
        ),
    ]
