# Generated by Django 5.2.4 on 2025-09-10 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0003_initial'),
        ('departamentos', '0004_alter_departamento_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='departamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='departamentos.departamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalactividad',
            name='departamento',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='departamentos.departamento'),
        ),
    ]
