# Generated by Django 5.2.4 on 2025-09-18 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0004_actividad_departamento_and_more'),
        ('departamentos', '0004_alter_departamento_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='evidencia',
        ),
        migrations.RemoveField(
            model_name='historicalactividad',
            name='evidencia',
        ),
        migrations.AlterField(
            model_name='actividad',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='departamentos.departamento'),
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='actividades/evidencias/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='actividades.actividad')),
            ],
        ),
    ]
