# Generated by Django 5.2.4 on 2025-11-02 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0005_historicalevidencia_historicalsolicitudreapertura'),
        ('programas', '0003_ciclo_nombre_historicalciclo_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='ciclo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programas.ciclo'),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='ciclo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programas.ciclo'),
        ),
        migrations.AddField(
            model_name='historicalactividad',
            name='ciclo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='programas.ciclo'),
        ),
        migrations.AddField(
            model_name='historicalevidencia',
            name='ciclo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='programas.ciclo'),
        ),
        migrations.AddField(
            model_name='historicalsolicitudreapertura',
            name='ciclo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='programas.ciclo'),
        ),
        migrations.AddField(
            model_name='solicitudreapertura',
            name='ciclo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programas.ciclo'),
        ),
    ]
