# Generated by Django 5.2.4 on 2025-09-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0005_remove_actividad_evidencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='editable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalactividad',
            name='editable',
            field=models.BooleanField(default=True),
        ),
    ]
