# Generated by Django 5.2.4 on 2025-11-04 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0006_actividad_ciclo_evidencia_ciclo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidencia',
            name='ciclo',
        ),
        migrations.RemoveField(
            model_name='historicalevidencia',
            name='ciclo',
        ),
        migrations.RemoveField(
            model_name='historicalsolicitudreapertura',
            name='ciclo',
        ),
        migrations.RemoveField(
            model_name='solicitudreapertura',
            name='ciclo',
        ),
    ]
