# Generated by Django 5.2.4 on 2025-09-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0007_solicitudreapertura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='estado',
            field=models.CharField(choices=[('Activa', 'Activa'), ('En Proceso', 'En Proceso'), ('Cumplida', 'Cumplida'), ('No Cumplida', 'No Cumplida')], default='Activa', help_text='Estado actual de la actividad', max_length=15),
        ),
        migrations.AlterField(
            model_name='historicalactividad',
            name='estado',
            field=models.CharField(choices=[('Activa', 'Activa'), ('En Proceso', 'En Proceso'), ('Cumplida', 'Cumplida'), ('No Cumplida', 'No Cumplida')], default='Activa', help_text='Estado actual de la actividad', max_length=15),
        ),
    ]
