# Generated by Django 5.2.4 on 2025-10-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0008_alter_actividad_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='nombre',
            field=models.CharField(blank=True, help_text='Nombre corto de la actividad', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalactividad',
            name='nombre',
            field=models.CharField(blank=True, help_text='Nombre corto de la actividad', max_length=255, null=True),
        ),
    ]
