# Generated by Django 5.2.4 on 2025-10-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0009_actividad_nombre_historicalactividad_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudreapertura',
            name='terminada',
            field=models.BooleanField(default=False),
        ),
    ]
