# Generated by Django 5.2.4 on 2025-09-01 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='historicaldepartamento',
            name='nombre',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
