# Generated by Django 5.2.4 on 2025-09-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0003_alter_departamento_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='historicaldepartamento',
            name='nombre',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
